name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    env:
      MP_TEST_ID: ${{ secrets.MP_TEST_ID }}
      MP_TEST_KEY: ${{ secrets.MP_TEST_KEY }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Run tests and generate coverage report
        run: pnpm test:cov

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          name: coverage-report
          token: ${{ secrets.CODECOV_TOKEN }}
